language: cpp

matrix:
  include:
    - os: osx
    - os: linux
      compiler: g++-7
      env:
        - MATRIX_EVAL="export CXX='g++-7'"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7

env:
  - CXXFLAGS='-Werror'

before_script:
  - eval "${MATRIX_EVAL}"
  - cd radiosity

script:
  - make
  - make run
