language: cpp

matrix:
  include:
    - os: osx
      osx_image: xcode9.1
      env:
        - MATRIX_EVAL="brew install llvm"
    - os: linux
      compiler: g++-7
      env:
        - MATRIX_EVAL="export CXX='g++-7'"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7

before_script:
  - export CXXFLAGS='-Werror'
  - eval "${MATRIX_EVAL}"
  - cd radiosity

script:
  - make
  - make run
  - make test
