language: cpp

matrix:
  include:
   - os: osx
   - os: linux
     compiler: g++-4.8

addons:
  apt:
    sources:
     - ubuntu-toolchain-r-test
    packages:
     - g++-4.8

env:
  - CXXFLAGS='-Werror'

before_script:
  - cd radiosity

script:
  - make
  - make run
