[package]
name = "rust_tracing"
version = "0.1.0"
authors = ["Michael Kaltschmid <kaltschmidmichael@gmail.com>"]

[dependencies]
ordered-float = "1.0.1"
lazy_static = "1.2.0"
crossbeam = "0.3"
num-traits = "0.2.6"
rand = "0.3.18"
rayon = "1.0.3"
