[package]
name = "rust_tracing"
version = "0.1.0"
authors = ["Michael Kaltschmid <kaltschmidmichael@gmail.com>"]

[dependencies]
lazy_static = "1.2.0"
crossbeam = "0.3"
rand = "0.6.0"
rayon = "1.0.3"
